// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb8rDqXHi2c7y1nTCkJOOy5o5luqtoC6E',
    appId: '1:413340696609:web:3f5cf59a91e10227c46360',
    messagingSenderId: '413340696609',
    projectId: 'chat-app-53a14',
    authDomain: 'chat-app-53a14.firebaseapp.com',
    storageBucket: 'chat-app-53a14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXRc1MCKGL81jVkuKpUZLrfqyOLZsYKxI',
    appId: '1:413340696609:android:7f22e0115ff0965ac46360',
    messagingSenderId: '413340696609',
    projectId: 'chat-app-53a14',
    storageBucket: 'chat-app-53a14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAplSHLNHcQQd6lnF-4MGMZ0BZK3Pb6ELg',
    appId: '1:413340696609:ios:af38c15eec3dc0bfc46360',
    messagingSenderId: '413340696609',
    projectId: 'chat-app-53a14',
    storageBucket: 'chat-app-53a14.appspot.com',
    iosClientId: '413340696609-s6c9mkfiv06ghoa562nml7k27m8453c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
